name: Checkout
on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  checkout:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@latest
