name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # introduction
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          # achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C # Display achievements with rank _ or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_display: detailed # Use compact/detailed display
          plugin_achievements_limit: 0 # Display all unlocked achievements (no limit)
          # plugin_achievements_ignored: _ # Hide _ achievement
          # traffic
          plugin_traffic: yes
          # languages
          plugin_languages: yes
          plugin_languages_ignored: Red, Rebol, J, Hack # List of languages to ignore
          plugin_languages_skipped: Hello-World # List of repositories to skip
          # plugin_languages_limit: _ # Display up to _ languages
          plugin_languages_sections: most-used, recently-used # Display most used and recently used
          # plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
          # plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage # Additionally display total bytes size and percentage
          # plugin_languages_threshold: _% # Hides all languages less than _%
          plugin_languages_indepth: no # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15 # Set maximum time for indepth analysis
          plugin_languages_categories: programming, data # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500 # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7 # Limit recently used stats to last week
          commits_authoring: ba004629@bac.qld.edu.au # Surnames or email addresses used to identify your commits
          # habits
          plugin_habits: yes
          plugin_habits_from: 200 # Use 200 events to compute habits
          plugin_habits_days: 14 # Keep only events from last 14 days
          plugin_habits_facts: yes # Display facts section
          plugin_habits_charts: yes # Display charts section
          plugin_habits_trim: yes # Trim unused hours on daily chart
          config_timezone: Australia/Brisbane # Set timezone
          # wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }} # Required
          plugin_wakatime_days: 7 # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4 # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com # Wakatime url endpoint
          plugin_wakatime_user: .user.login # User
