name: Metrics
on:
  workflow_dispatch:
  push: {
    branches: ["master", "main"]
  }
  schedule:
    - cron: '0 0 * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          plugin_achievements: yes
          plugin_achievements_threshold: X # Display achievements with rank S/A/B/C/X or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_display: compact # Use compact/detailed display
          plugin_achievements_limit: 0 # Display all unlocked achievements (no limit)
          # plugin_achievements_ignored: _ # Hide _ achievement
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_ignored: CSV, "Jupyter Notebook", SQL, SVG # List of languages to ignore
          # plugin_languages_skipped: _ # List of repositories to skip
          plugin_languages_limit: 8 # Display up to _ languages
          plugin_languages_sections: most-used # Display most used and recently used ("most-used, recently-used")
          plugin_languages_details: percentage # Additionally display total bytes size and percentage ("bytes-size, percentage")
          plugin_languages_threshold: 0% # Hides all languages less than _%
          plugin_languages_indepth: no # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: ba004629@bac.qld.edu.au, johnsdieckmann@gmail.com
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time # Display time and projects sections, along with projects graphs ("time, projects, projects-graphs")
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: .user.login
          plugin_lines: yes
